#!/usr/bin/env python
"""Generate golden values for test/gaussian/golden_values.jl from the GTN
reference implementation.

Run ONCE with:
    ~/.pyenv/versions/miniforge3-25.1.1-2/bin/python test/gaussian/generate_golden.py

Outputs Julia-literal snippets on stdout; they are embedded (with provenance
comments) in test/gaussian/golden_values.jl.

Golden cases (chosen to NOT duplicate the goldens already embedded by earlier
tasks — T2's test_kernel.jl uses the L=4 VACUUM with ix=[1,2] 0-based; T15's
test_majorana_chain.jl uses the SO(2)/kraus((0,cos,sin)) unitary branch):
  (a) P_contraction_2 on the L=4 OCCUPATION PATTERN "0110" state with
      Upsilon = kraus([0.6, 0.8, 0.0]) at ix=[3,4] 0-based Majoranas
      (straddling modes 2-3; Julia 1-based ix=[4,5]).
  (b) von_Neumann_entropy_m (nats) of the analytically-specified L=2 Gamma:
      vacuum rotated by the Givens rotation R(theta=pi/3) on Majoranas 1,2
      (0-based), subregion = fermion mode [0].
      Analytic value: 2*log(2) - 0.75*log(3).
"""
import sys
import datetime

import numpy as np

sys.path.insert(0, "/Users/hainingpan/GTN")
from GTN import GTN, P_contraction_2  # noqa: E402


def occupation_covariance(bits):
    """Gamma = direct sum of [[0, s],[-s, 0]] with s=+1 unoccupied, -1 occupied.

    Same convention as GTN.get_C_f / Julia occupation_covariance (T2-verified):
    Gamma[2i, 2i+1] = +1 (0-based)  <=>  <c_i^dag c_i> = 0.
    """
    L = len(bits)
    G = np.zeros((2 * L, 2 * L))
    for i, b in enumerate(bits):
        s = -1.0 if b else 1.0
        G[2 * i, 2 * i + 1] = s
        G[2 * i + 1, 2 * i] = -s
    return G


def fmt_julia_matrix(name, M):
    rows = []
    for r in range(M.shape[0]):
        rows.append(" ".join("%.17g" % M[r, c] for c in range(M.shape[1])))
    body = ";\n    ".join(rows)
    return "const %s = [\n    %s\n]" % (name, body)


def main():
    print("# Generated by test/gaussian/generate_golden.py on %s"
          % datetime.date.today().isoformat())
    print("# Python: %s" % sys.version.split()[0])
    print("# numpy: %s" % np.__version__)
    print()

    # ── (a) contraction golden ───────────────────────────────────────────
    L = 4
    gtn = GTN(L=L, history=False, c=[1, 1, 1])
    bits = [False, True, True, False]  # "0110"
    Gamma = occupation_covariance(bits)
    Upsilon = gtn.kraus(np.array([0.6, 0.8, 0.0]))
    ix = [3, 4]  # 0-based Majorana indices (Julia 1-based: [4, 5])
    ix_bar = [i for i in range(2 * L) if i not in ix]
    P_contraction_2(Gamma, Upsilon, np.array(ix), np.array(ix_bar))
    print("# (a) P_contraction_2 output: '0110' occupation state, "
          "kraus([0.6,0.8,0.0]), ix=[3,4] 0-based")
    print(fmt_julia_matrix("GOLDEN_CONTRACTION_0110", Gamma))
    print()

    # ── (b) entropy golden ───────────────────────────────────────────────
    L2 = 2
    gtn2 = GTN(L=L2, history=False, c=[1, 1, 1])
    theta = np.pi / 3
    O = np.eye(2 * L2)
    O[1, 1] = np.cos(theta)
    O[1, 2] = -np.sin(theta)
    O[2, 1] = np.sin(theta)
    O[2, 2] = np.cos(theta)
    G2 = occupation_covariance([False, False])  # vacuum
    G2 = O @ G2 @ O.T
    S = gtn2.von_Neumann_entropy_m([0], G2)
    analytic = 2 * np.log(2) - 0.75 * np.log(3)
    print("# (b) von_Neumann_entropy_m([0], Givens(pi/3)-rotated L=2 vacuum)")
    print("#     analytic 2log(2) - 0.75log(3) = %.17g (|diff| = %.3g)"
          % (analytic, abs(S - analytic)))
    print("const GOLDEN_ENTROPY_GIVENS_PI3 = %.17g" % S)


if __name__ == "__main__":
    main()
