# test/gaussian/golden_values.jl
# Python-generated golden values for the Gaussian backend, cross-checked
# against the Julia kernel. Deterministic algebra ONLY (no RNG-dependent
# trajectories — cross-language RNGs differ).
#
# PROVENANCE: all literals below were generated by
#   ~/.pyenv/versions/miniforge3-25.1.1-2/bin/python test/gaussian/generate_golden.py
# on 2026-07-12 (Python 3.12.9, numpy 2.4.2), using the GTN reference
# implementation at /Users/hainingpan/GTN (GTN.GTN, GTN.P_contraction_2).
#
# NOTE — goldens already embedded by earlier tasks (NOT duplicated here):
#   - test_kernel.jl (T2):        P_contraction_2 on the L=4 VACUUM,
#                                 kraus([0.6,0.8,0.0]), ix=[1,2] 0-based.
#   - test_oracle.jl (T5):        GTN.density_matrix of a Givens(0.7)-rotated
#                                 L=2 vacuum (ED-oracle golden).
#   - test_majorana_chain.jl (T15): kraus((0,cos φ,sin φ)) SO(2) unitary
#                                 branch, φ=0.7, 4×4 vacuum.
# This file adds NEW cases: a contraction from a NON-vacuum (occupied-pattern)
# initial Γ, and a von_Neumann_entropy_m golden with an analytic closed form.
#
# Standalone: julia --project=. -e 'include("test/gaussian/golden_values.jl")'

using Test
using LinearAlgebra
using QuantumCircuitsMPS

const QCM_GOLD = QuantumCircuitsMPS

# ── Generated literals (verbatim generate_golden.py output) ─────────────────

# (a) P_contraction_2 output: '0110' occupation state, kraus([0.6,0.8,0.0]),
#     ix=[3,4] 0-based (Julia 1-based ix=[4,5], straddling modes 2-3).
const GOLDEN_CONTRACTION_0110 = [
    0 1 0 -0 -0 0 0 0;
    -1 0 0 -0 -0 0 0 0;
    0 0 0 -0.80000000000000004 -0 -0.59999999999999998 0 0;
    0 0 0.80000000000000004 0 -0.59999999999999998 0 0 0;
    0 0 0 0.59999999999999998 0 -0.80000000000000004 0 0;
    0 0 0.59999999999999998 -0 0.80000000000000004 0 0 0;
    0 0 0 -0 -0 0 0 1;
    0 0 0 -0 -0 0 -1 0
]

# (b) von_Neumann_entropy_m([0], Givens(π/3)-rotated L=2 vacuum), nats.
#     Analytic: 2log(2) − 0.75log(3); Python |diff| vs analytic = 0.
const GOLDEN_ENTROPY_GIVENS_PI3 = 0.56233514461880829

@testset "Python golden values (generate_golden.py)" begin

    @testset "contraction on '0110' occupation state matches P_contraction_2" begin
        bits = [false, true, true, false]  # "0110"
        Γ = QCM_GOLD.occupation_covariance(bits)
        Υ = QCM_GOLD._kraus((0.6, 0.8, 0.0))
        QCM_GOLD.gaussian_contraction!(Γ, Υ, [4, 5])  # Python ix=[3,4] 0-based
        @test maximum(abs.(Γ .- GOLDEN_CONTRACTION_0110)) < 1e-14
        # Post-contraction state stays pure and antisymmetric
        @test maximum(abs.(Γ .+ transpose(Γ))) < 1e-14
        @test maximum(abs.(Γ * Γ + I)) < 1e-12
    end

    @testset "von Neumann entropy matches von_Neumann_entropy_m + analytic" begin
        θ = π / 3
        O = Matrix{Float64}(I, 4, 4)
        O[2, 2] = cos(θ); O[2, 3] = -sin(θ)
        O[3, 2] = sin(θ); O[3, 3] = cos(θ)
        Γ = O * QCM_GOLD.vacuum_covariance(2) * transpose(O)
        Γ .= (Γ .- transpose(Γ)) ./ 2
        S = QCM_GOLD.subsystem_entropy(Γ, [1, 2])  # mode 1, nats
        @test abs(S - GOLDEN_ENTROPY_GIVENS_PI3) < 1e-12
        @test abs(S - (2log(2) - 0.75log(3))) < 1e-12
        @test abs(GOLDEN_ENTROPY_GIVENS_PI3 - (2log(2) - 0.75log(3))) < 1e-14
    end
end
